### ISSUE TITLE
Light wallet iOS APP suggestion

### ISSUE THREAD

**Issue by Pucvola** [DeFiCh/wallet#1606]
#### I would love to see these functionalities in the light wallet app:

1. Displaying Fiat value on balances page

2. Ability to set (or automatic ones) App notifications in case collateralization ratio drops, to eliminate necessity to manually check app all the time. And to eliminate uneccessary vault liqudation.

3. Ability to sign transactions with face ID, not only passcode, which is exhausting.

#### Why is this needed:
Ease of use. UX

Also thanks a lot for the excelent app.
Appreciate your hard work.

**Comment by thedoublejay** [comment]
Hi @Pucvola, thanks for your feedback. Just some thoughts on it:
1. Yes, this one is planned on the next releases.
2. App notifications, for now, is not yet planned as of the moment. One requirement for app notifications would be to have a "centralized server" that tracks all activities and pushes notifications. Currently, we don't want to do it due to nature of our app (decentralized). But, we're checking on other ways on how can this be implemented.
3. This one we consider but we didn't push thru due to security issues. We want to separate the privacy feature (e.g, Face ID, fingerprint etc.) and passcode. We went with security over convenience especially on a mobile device.

Appreciate the feedbacks and support, we will continue improving on the app and provide better UX to our users.
