### ISSUE TITLE
Change `Total Interest Amount` to `Total Annual Interest` on Borrow Loan screen for clarity

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/wallet#1637]
#### What UI/UX improvements would you like to be implemented: 

To change label `Total Interest Amount` to `Estimated Annual Interest`. 

Currently, `Total Interest Amount` can be misleading because users might think this is the immediate interest he/she has to pay, which can impact the amount of tokens he/she chooses to mint, especially in situations where a large loan amount is involved.

![telegram-cloud-photo-size-5-6165686520372112978-y](https://user-images.githubusercontent.com/66629826/145347698-8b25cb89-d939-4bda-a237-9ce82ab66bdc.jpg)

**Comment by pierregee** [comment]
@ngyingzhong Just to confirm, are we going to change the wording here, too?
![image](https://user-images.githubusercontent.com/13292662/145362161-170d9415-0d56-48e1-91b8-7e5fc8736e62.png)

**Comment by pierregee** [comment]
@ngyingzhong just to confirm, aren't we going to update the wording here, too?
![image](https://user-images.githubusercontent.com/13292662/145364881-90a1420e-0ce1-43fe-a89c-9f3ec386f5b7.png)

**Comment by ngyingzhong** [comment]
@pierregee I don't think there's a need to change the wording in this page. In this context, it's quite evident that whatever amount you see on screen (e.g. 0.00023 dTSLA) is the amount of interest you have incurred. The reason I proposed the change for the Borrow Loan screen is because it's a loan overview page — in this "summary" view, I thought we should be careful with the details.

**Comment by kyleleow** [comment]
@ngyingzhong i was reviewing the PR fix for this then i realized currently the there is a bug that the `Total annual interest` is a flat amount. It does not change with the amount of loan that you plan to take. This is currently tracked in #1745 

Aside from this, i am not sure if calling it total annual interest is a good idea, because the interest we used to display in `Total loan + interest` is the interest per block. 

Interest per block = ( (vault interest + loan token interest) / 100 ) / (365 days * 2880 blocks in mainnet per year)

If we change to `Total annual interest`, we will need to display the value to be:
((vault interest + loan token interest) / 100 ) * (loan amount) ?

**Comment by ngyingzhong** [comment]
@kyleleow If `total interest amount` and `total loan + interest` is the interest for 1 block, not the entire year, it would invalidate my initial comments. My initial understanding was that it is reflecting the total annual interest amount, hence the feedback to change the text.

**Comment by ngyingzhong** [comment]
Let's calculate the annual interest on the front end, and display

- `Estimated annual interest`
- `Total loan + annual interest`
