### ISSUE TITLE
dBABA - lost money ?!

### ISSUE THREAD

**Issue by Tom7510** [DeFiCh/wallet#1661]
Hi,
I minted BABA in order to pay back a BABA loan which was still existing.
Then I payed back my BABA loan  (1.34 Baba) and the transaction was accepted.
After the transaction was done, there was again the same abount ob BABA as before on the loan!!!
I tried again, same again.
So I "shot" obviously 2x 1.34 BABA into a black hole and the loan was no reduced - what's going on here?!
Please check my vault and correct this issue!
I obvously lost more  2.64 BABA,  honesly with all that issues, I'll phase out of this experiment soon since I lost more than I won within the last 4 days !!!???
I'm in the inner circle of Julian an probably will complain during the next session.
//Thomas 

My vault: 7d45468c70910d25e017d660e1a9db94bf101b6a2a6e16642695af7398c2e1b8

**Comment by ngyingzhong** [comment]
Hi @Tom7510, are you able to recall the **first time** you minted a dBABA token? It would be very helpful for investigation if you could provide the date and estimated time of day the transaction took place. Thanks!

**Comment by ngyingzhong** [comment]
Hi @Tom7510, thanks for raising the issue. We have investigated this by looking through the transactions in the [address page ](https://defiscan.live/address/df1q2yw2sehgexqxr2pqe0x83zgflmuxdr4q84n62d) and can confirm that the loan payback transactions are correctly recorded and reflected on your vault and your address balance. The reason why the outstanding dBABA amount remained in your vault even after loan payback is because the total dBABA loan taken across the past few days was more than the total dBABA payback made. 

Total Loan taken (across period): ~5.46 dBABA
Total Loan Payback: ~1.98 dBABA
Outstanding: ~1.98 dBABA

Hope this clarifies, thanks!

**Comment by wmbst** [comment]
When you mint BABA you increase your loan. If you pay back your loan with the newly minted tokens, you are at the starting point again. That's how it is supposed to be and no bug.
