### ISSUE TITLE
`e2e` - slow tests - should check network details after intercepting stats call

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1777]
#### What would you like to be added:
Improve test speed for `Wallet - Network detail screen - outside wallet contextshould check network details after intercepting stats call` in `networkDetails.spec.ts`. Currently it takes around 1min.

**Comment by kyleleow** [comment]
I think this line is the culprit, reason for the long timeout is because smallest unit displayed in `Last synced` UI is minutes, hence that test is written to check if a minute has passed

https://github.com/DeFiCh/wallet/blob/4893a9bd48520375e34e94014bc8a8c1db02c3c2/mobile-app/cypress/integration/functional/wallet/settings/networkDetails.spec.ts#L113

**Comment by kyleleow** [comment]
@thedoublejay i think no way to get around this waiting time, unless we don't test if the UI changes after 1 min
