### ISSUE TITLE
Auction Card - Min. next bid

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1985]
On Auction cards, we need to put the prices based on DEX values on the Min. next bid. Check epic for more info #1856 
![image](https://user-images.githubusercontent.com/25013382/150893798-26940da2-196d-4135-8db4-fa4b238e1ff0.png)

**Comment by kyleleow** [comment]
@thedoublejay questions, when should we use DEX values and when should we use `activePrice`?
Because in loans screen > vault details we are using `activePrice`
![image](https://user-images.githubusercontent.com/40191153/151106902-c758f61e-8b4d-4fa4-a8d3-54ce017c888a.png)

And then suddenly in auction we use DEX values?
![image](https://user-images.githubusercontent.com/40191153/151106965-d3690947-cdd7-4884-b6e9-51a92aef9af3.png)

**Comment by thedoublejay** [comment]
@kyleleow this should be DEX price also. The only time we use oracle price should be on taking a loan. Need more clarity with @ngyingzhong
