### ISSUE TITLE
`token detail` - reenable for DFI

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2395]
#### What would you like to be added:
On portfolio page, clicking on a token card will open Token Detail page. Token Detail page shows all operations you can do (e.g, Add Liquidity, Swap etc.) and balance of the token.

For DFI, we don't show this screen. We would like to re-enable this. 

- [ ] Clicking on the DFI card from portfolio page should go to Token Detail
- [ ] Should show total balance of DFI
- [ ] Show following options:
- [ ] Send to other wallet
- [ ] Receive DFI
- [ ] Swap token

**Comment by thedoublejay** [comment]
@rox1338 you can check out this one if you're looking

**Comment by rox1338** [comment]
on it

**Comment by rox1338** [comment]
So if just "re-enable" the DetailScreen for DFI it looks like this:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/100290452/167408529-a602df8b-7a5c-4748-a0a9-bb7a49e793ce.png">

I would assume that we still want to keep the "Convert to UTXO" option.
I also think that we don't want to add the "Add to Liquidity Pool" option because we have no fitting UI-flow for this.
Do we want to add the "Swap token" option which would lead to a SwapScreen with DFI prefilled in the FROM field?
@thedoublejay

**Comment by thedoublejay** [comment]
@rox1338 Yep! convert should be ok. We can omit add liquidity also. 

Swap - Yup! You can use the same flow as other tokens.

**Comment by thedoublejay** [comment]
@rox1338 Some comments:

1. Token Detail - DeFiChain token link is wrong - when opening DeFiScan
2, Portfolio - DFI Border card is not rounded anymore 

When creating PR, please ensure that all changes will not cause a regression issue and it's well tested. Thanks!

**Comment by rox1338** [comment]
@thedoublejay I think this can be closed
