### ISSUE TITLE
loan payback deactivated during halted vaults

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/wallet#2822]
#### What happened:
vaults got halted due to inactive DFI oracle. On the halted vault, the "manage loans" button got deactivated so you could not pay back loans.

#### What you expected to happen:
Since FCR, paying back loans is always possible (even during halted vaults) if you use the dToken itself (no payback via DFI). So the button should be active and paying back should be possible.

#### How to reproduce it (as minimally and precisely as possible):
unfortunatly you can only reproduce it when vaults are halted. so no easy way to reproduce it.

#### Anything else we need to know?:
paying back loans during halted vaults is crucial cause a change in active oracles (f.e. vault is halted cause stock oracle is down, but DFI oracle is up and DFI dropping hard) could immediatly liquidate your vault once its back up. Many user rely on the possibility to payback loans to keep their vaults stable (aka they don't have additional collateral available to add, but dTokens in the LM)

**Comment by kyleleow** [comment]
Hi kuegi, thanks for creating an issue, the team is aware of this in #2821 and has applied a fix in this PR #2819 , it will be available in the next release.

Meanwhile, the disabled `Manage loan` button is only a shortcut, user is still able to pay back loan by going to Vault detail screen > Loan tab and payback from there

This is reproducible in Playground environment by taking a loan of dTR50 in which it behaves as huge price fluctuation dToken for testing purposes.

Closed due to replicate of #2821

**Comment by zhanglingbin** [comment]
![image](https://user-images.githubusercontent.com/32158084/169473556-0c018d98-b59b-4935-82cb-c496d723daee.png)

**Comment by kyleleow** [comment]
Hi @zhanglingbin as mention in my previous comment, `Managed loans` button will be enable when vault is halted in next release, you can still access payback loan screen through Vault detail screen > Loans tab 
![image](https://user-images.githubusercontent.com/40191153/169473798-8c72192a-576a-45b5-a90a-c09116f10a6c.png)

**Comment by zhanglingbin** [comment]
got it, thank you sir
