### ISSUE TITLE
`Loans` - change in col ratio when input 0

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#3231]
https://user-images.githubusercontent.com/65014479/182054749-ecca5015-fe94-4b25-a60a-dc92700bf93f.mov

#### What happened:
• When adding collateral to vault, change in **resulting collateralization ratio** when user enters 0

#### What you expected to happen:
• **Resulting collateralization ratio** should not change if user inputs 0

#### How to reproduce it (as minimally and precisely as possible):
• `LOANS` > `Your vaults` tab > at Vault, select `MANAGE LOANS` > at **Vault Detail** screen, select `EDIT COLLATERAL` > `+ ADD TOKEN AS COLLATERAL` > select `dUSDC` > input **0** dUSDC > grey `X` > input **0** dUSDC > error: change in resulting collateralization ratio when user enters 0

• `LOANS` > select vault > `EDIT COLLATERAL` > `+ ADD TOKEN AS COLLATERAL` > at **dUSDC** card, select + > input **0** dUSDC > grey `X` > input **0** dUSDC > error: change in resulting collateralization ratio when user enters 0

**Comment by kyleleow** [comment]
Currently collateralization ratio displayed throughout the app is using `collateralRatio` from the ocean api, but that value is rounded to nearest percent. 

When LW is calculating resulting col ratio in add or remove collateral form, we are taking the collateral value and loan value up to 8 decimal places, even when the input amount is `0`. Hence, what user experienced right now caused by the difference in terms of precision between the number that LW display and the one we calculated

Possible solution is to replace all collateralization ratio display throughout the app to use `informativeRatio` from the api, in which that ratio is in 8 dp
