### ISSUE TITLE
Defichain value inaccuracies project wide (new USDT pool bug?)

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/wallet#3308]
This bug report is not from me, but came in via email from RuledoCino.

#### What happened:

When the dUSDT-DUSD pool was made active the entire community's Lite Wallet values show in USD (which is actually dUSDT I found from the code) JUMPED up a large amount.
I verified this with many users.
My portfolio jumped up thousands of dollars but it was not real.
I checked the DEX and dUSDT was normally priced.
An example is that 14.67382578 dUSDC is showing as $17.45 in the Lite Wallet.

![unnamed](https://user-images.githubusercontent.com/280505/184871292-21f485d8-def9-4b17-823a-7ad17aae21d1.png)

#### What you expected to happen:
14.67382578 dUSDC should be showing as around $14.67 in Light Wallet

#### How to reproduce it (as minimally and precisely as possible):

Just hold dUSDC coin in Light Wallet and see watch the dollar value.

**Comment by izzycsy** [comment]
Hi @uzyn , thanks for the feedback, please give the team time to investigate.

**Comment by kynkong91** [comment]
Hi, we have investigated this issue -this is not a bug, but an intricacy of DEX.

Currently on the LW, values that are denominated in USD. But in reality, the value of "USD" is obtained from USDT, because as a DEX, we need to get the value of USD from somewhere as well. In usual time, this system works fine as 1 USD:1 USDT.

However, the introduction of the dUSDT and dUSDC pools, have greatly altered the value of USDT itself (due to influx in demand). For example, when this issue was first surfaced by one of the community member, 1 USDT was equivalent to 1.23 USD. As all the values in LW are actually calculated using USDT, even though it is labelled USD, the value of user's portfolio seemed to when up in USD terms.

There are a few potential ways to approach this:
- Obtain USD value from external sources like coingecko (but the issue is that we will be at the mercy of the reliability of these systems. If these systems goes down, then the entire LW will be affected. And these external sources have actually had outages befores)
- Change the parts labelled as USD to USDT on the LW, so that users are aware that the value are denominated in USDT. However this solution will be counterintuitive to those new to DEX (given that their mental model would be 1 USD : 1 USDT always), and so we will concurrently post out a public education post explaining about the intricacy of DEX.

After some discussion, we have opted for option 2. We will update the community when we pushed out a LW update for this.
