### ISSUE TITLE
`settings` - main page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#56]
#### What would you like to be added:
Settings page with some features
#### Why is this needed:
- [ ] Network Switcher
- [ ] Exit Wallet
- [ ] Language Selector

![image](https://user-images.githubusercontent.com/25013382/119120042-65a5f800-ba5e-11eb-87b1-e61e927d3d9f.png)

**Comment by fuxingloh** [comment]
- [ ] @thedoublejay remove language selector that's a system-level protocol, (might need to introduce another indicator saying how to change it, but we should never re-implement system-level protocols)

/assign @thedoublejay but not ready to be worked on yet there is still some grey area. Mostly due to how we going to set up an alternative network for testing. I will mark this as ready when I have an idea of how to deal with it.
