### ISSUE TITLE
`token detail` - updated summary

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#941]
#### What would you like to be added:
Update token detail summary. Only the upper section since we don't support transactions per token yet.

https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=698%3A14412&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=665%3A12670&show-proto-sidebar=1

![image](https://user-images.githubusercontent.com/25013382/135005504-600fb268-35ae-460c-a1c9-708273e87d96.png)

**Comment by kyleleow** [comment]
@thedoublejay token detail page for unified DFI will be different compared to others.
 
Since we don't have unified DFI ready, can i make all token details page to have the same design first? Meaning we will have token detail page for DFI Token and UTXO separately

![image](https://user-images.githubusercontent.com/40191153/135053679-74409790-0026-4237-91f5-b273b4f722b4.png)

**Comment by kyleleow** [comment]
@thedoublejay should i disable "SEND" button when DFI is less than 0.1? or it is just a non-zero check?

Asking this because the token detail screen now has a disabled state to the SEND button
![image](https://user-images.githubusercontent.com/40191153/135071827-b4081040-770d-441f-8925-ced8da7f51a0.png)
